[supabase]
url = "https://wilzxzfpvywicvyplmsk.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndpbHp4emZwdnl3aWN2eXBsbXNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NDUzOTYsImV4cCI6MjA2NjUyMTM5Nn0.QDp4Suf3UduOBrfqRpuCXUJxnp4BTTc0iVfU9cTc1Xg"
